version: "3.8"

services:
  postgres:
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
  frontend:
    build:
      context: ./mebay-app
      dockerfile: Dockerfile.Development
    ports:
      - "80:80"
  backend:
    build:
      context: ./mebay-backend/MeBay
      dockerfile: Dockerfile.Development
    ports:
      - "5001:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=postgres;Username=postgres;Password=postgres
      - JwtSettings__Key=ThisKeyIsMySecretButIWillNeverUseThis
      - PORT__5001
    depends_on:
      - postgres
