name: CI - Frontend

on:
  push:
    branches: ["main, dev"]
  pull_request:
    branches: ["main, dev"]

defaults:
  run:
    working-directory: mebay-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: npm ci
      - name: Testing
        run: npm run test
      - name: Build
        run: npm run build
