name: CD - Backend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

defaults:
  run:
    working-directory: mebay-backend/MeBay

jobs:
  build:
    name: Test and build Backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Check code format
        run: |
          dotnet format
          incorrect_format=`git diff --exit-code`
          if [ ! -z $incorrect_format ]
          then
            echo "Code format is not correct"
            echo "Please correct the following changes"
            echo "at $incorrect_format"
            exit 1
          fi
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
  deploy:
    name: Deploy Backend
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --strategy immediate
        env:
          FLY_API_TOKEN: ${{ secrets.BACKEND_API_TOKEN }}
